name: Deploy React to S3

on:
  push:
    branches: ['Woody-refactor']
  pull_request:
    branches: ['Woody']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          VITE_SERVER: ${{ secrets.VITE_SERVER }}
          VITE_JSON_SERVER: ${{ secrets.VITE_JSON_SERVER }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://react-news-stand-bucket --delete
